workflows:
  ios-workflow:
    name: iOS Build
    environment:
      xcode: latest
      node: latest
      cocoapods: default
      vars:
        XCODE_PROJECT: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
        BUNDLE_ID: "com.solarin.uvtracker"
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_PROJECT_PATH: "ios/App/App.xcodeproj"
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build web app
        script: |
          npm run build
      - name: Sync Capacitor
        script: |
          npx cap sync ios
      - name: Build iOS app
        script: |
          xcodebuild build -workspace "$XCODE_WORKSPACE" -scheme "$XCODE_SCHEME" -configuration Release -destination generic/platform=iOS -archivePath build/ios/App.xcarchive
      - name: Create IPA
        script: |
          xcodebuild -exportArchive -archivePath build/ios/App.xcarchive -exportPath build/ios/ipa -exportOptionsPlist exportOptions.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      email:
        recipients:
          - mviniciusortiz4@gmail.com 