workflows:
  ios-workflow:
    name: iOS Build (Simulator)
    environment:
      xcode: latest
      node: latest
      cocoapods: default
      vars:
        XCODE_PROJECT: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
        BUNDLE_ID: "com.solarin.uvtracker"
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_PROJECT_PATH: "ios/App/App.xcodeproj"
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build web app
        script: |
          npm run build
      - name: Sync Capacitor
        script: |
          npx cap sync ios
      - name: Build iOS app for simulator
        script: |
          xcodebuild build -workspace "$XCODE_WORKSPACE" -scheme "$XCODE_SCHEME" -configuration Debug -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest'
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      email:
        recipients:
          - mviniciusortiz4@gmail.com 