

services:
  # Development service
  app-dev:
    build:
      context: .
      target: builder
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
    profiles:
      - dev

  # Production service
  app-prod:
    build:
      context: .
      target: runner
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    profiles:
      - prod

  # Development with hot reload
  app-dev-hot:
    build:
      context: .
      target: builder
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev -- --host 0.0.0.0
    profiles:
      - dev-hot

networks:
  default:
    name: sol-vita-tracker-network 